version: '3.8'

services:
  whatsapp-gateway:
    build: .
    ports:
      - "8000:8000"  # Python FastAPI (WhatsApp Gateway)
      - "3000:3000"  # Node.js Baileys WebSocket server
    volumes:
      - whatsapp_auth:/app/auth_info  # Persistent WhatsApp authentication
      - ./logs:/app/logs              # Container logs
      - ./config:/app/config          # Configuration files
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp_auth:
    driver: local
