services:
  whatsapp-gateway:
    build: .
    container_name: whatsapp-gateway
    ports:
      - "3051:3051"  # Python FastAPI (WhatsApp Gateway)
      - "3050:3050"  # Node.js Baileys WebSocket server
    volumes:
      - whatsapp_auth:/app/auth_info  # Persistent WhatsApp authentication
      - ./logs:/app/logs              # Container logs
      - ./config:/app/config          # Configuration files
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
      - PYTHON_API_PORT=3051
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3051/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  whatsapp_auth:
    driver: local
