
# Model Configuration
model:
  fire_detection:
    path: "apps/ai_detection/model/smoke-v2-v12n-20250521.pt"
    confidence_threshold: 0.5

# Video Input Configuration
video:
  stream_url: "data/videos/Security Camera Video of Fire at WLNE.mp4"
  output_directory: "data/violations"

# WhatsApp API Configuration
whatsapp:
  api:
    python_server_url: "http://localhost:8000"
    baileys_server_url: "http://localhost:3000"
  contact_name: "Fares Voda"
  phone_number: "+201025939307"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  reload: false

# Logging Configuration
logging:
  level: "INFO"
  file_path: "logs/fire_detection.log"

# Detection Notification Settings
notification:
  initial_alert_counter: 1
  default_priority: "High"

# Device Configuration
device:
  prefer_cuda: true