model:
  fire_detection:
    path: "models/firesmoke_v4-8m_20241223.pt"
    confidence_threshold: 0.5
video:
  stream_url: "data/videos/Security Camera Video of Fire at WLNE.mp4"
  output_directory: "data/violations"

whatsapp:
  api:
    python_server_url: "http://localhost:8000"
    baileys_server_url: "http://localhost:3000"
  phone_number: "+201025939307"
  send_images: false
  send_videos: false  
  send_text: false  

server:
  host: "0.0.0.0"
  port: 8001
  reload: false

logging:
  level: "INFO"
  file_path: "logs/fire_detection.log"

notification:
  initial_alert_counter: 1
  default_priority: "High"

device:
  prefer_cuda: true